# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

	config.vm.box = "bento/ubuntu-20.04"
	config.vm.define "web" do |web|
		web.vm.hostname = "web-server"
		web.vm.network "private_network", ip: "192.168.56.2"
		web.vm.provision "shell", inline: <<-SHELL
			apt update -y
			apt upgrade -y
			apt install -y apache2 -y
			apt install vim -y
		SHELL
	end

	config.vm.define "sql" do |sql|
		sql.vm.hostname = "sql-server"
		sql.vm.network "private_network", ip: "192.168.56.3"
		sql.vm.provision "shell", inline: <<-SHELL
			apt update -y
			apt upgrade -y
			apt install sqlite3 -y
			if [[ $? -ne 0 ]]; then
			echo "Failed to install sqlite3, executing apt update --fix-missing"
			apt update --fix-missing -y
			apt install sqlite3 -y
			fi
		SHELL
	end

	config.vm.define "lb" do |lb|
		lb.vm.hostname = "loadbalancer"
		lb.vm.network "private_network", ip: "192.168.56.4"
		lb.vm.provision "shell", inline: <<-SHELL
			apt update -y
			apt upgrade -y
		SHELL
	end

end
